### PR TITLE
Refactor git tags workspace tests to table tests

### PR DESCRIPTION
**Pull request by mjyocca**
## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ TFE_ADDRESS="https://example" TFE_TOKEN="example" TF_ACC="1" go test ./... -v -tags=integration -run TestFunctionsAffectedByChange

...
```

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202780502874161

### CODE REVIEW

**Review by annawinkler — APPROVED** [review]
Wow so pretty! 🤩

**Comment by annawinkler** [comment]
It looks like there are some test failures, some that might be related to these tests?

**Comment by mjyocca** [comment]
> It looks like there are some test failures, some that might be related to these tests?

Weird these tests pass locally. Seems like `OAUTH_CLIENT_GITHUB_TOKEN` is missing?

**Comment by brandonc** [comment]
That is odd. We do have one set in the repo for GHA

Screen Shot 2022-08-17 at 10 18 45 AM

**Comment by annawinkler** [comment]
@mjyocca Could you please resolve the conflict? Thanks! ✨

**Review by annawinkler — DISMISSED** [review]
:shipit:

**Comment by mjyocca** [comment]
@annawinkler looks like still getting errors with `export a valid OAUTH_CLIENT_GITHUB_TOKEN`. Assuming #505 is the fix?

**Comment by annawinkler** [comment]
Hm... I'm seeing this test fail:

```
=== RUN   TestAuditTrailsList/using_since_query_param
    audit_trail_integration_test.go:88: 
        	Error Trace:	/home/runner/work/go-tfe/go-tfe/audit_trail_integration_test.go:88
        	Error:      	"0" is not greater than "0"
        	Test:       	TestAuditTrailsList/using_since_query_param
    --- FAIL: TestAuditTrailsList/using_since_query_param (1.42s)
FAIL TestAuditTrailsList/using_since_query_param (1.42s)
```

**Review by annawinkler — APPROVED** [review]
:shipit:

**Pull request merged**
