### PR TITLE
resources list

### PR DESCRIPTION
**Pull request by estenssoros**
## Description

This is my first time submitting a PR to a mature product like go-tfe. Any feedback would be much appreciated.
I created this PR because I would like to be able to list the resources available in a workspace.

## Testing plan

1.  _Describe how to replicate_
1.  _the conditions_
1.  _under which your code performs its purpose,_
1.  _including example code to run where necessary._

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- [API documentation](https://www.terraform.io/docs/cloud/api/xxxx.html)
- [Related PR](https://github.com/terraform-providers/terraform-provider-tfe/pull/xxxx)

## Output from tests

I could use some help figuring out how to test this. Do I need to stand up a terraform enterprise deployment? Is there a docker image available?

I also tied to emulate other tests that I have seen in this repo. Let me know if I should add other or need to change what I have.

```
$ go test

...
```

### CODE REVIEW

**Comment by estenssoros** [comment]
Thanks @brandonc! Sorry I missed the notification for this (I need to figure out how to set that up). I will add this to my todo list

**Comment by barrettclark** [comment]
@estenssoros I see that you've added a commit to address @brandonc's feedback. Thank you for doing that. It looks like there is a conflict now, though. Can you resolve that?

**Review by brandonc — CHANGES_REQUESTED** [review]
One more bit of feedback: list options are not required, so can you make the `ResourceListOptions` argument a pointer type? This is a convention we adopted as of the 1.0 release. Thanks!

**Comment by annawinkler** [comment]
Hi @estenssoros 👋 Thank you for your contribution! We'd like to get this PR merged, and to do so, we'll first need you to sign to Contributor License Agreement (you can click on the link in the workflow to do this). Next, there are a few small things to update in this PR:

- Update `ResourceListOptions` per this [comment](https://github.com/hashicorp/go-tfe/pull/265#pullrequestreview-1011055784)
- Add a [changelog](https://github.com/hashicorp/go-tfe/blob/main/CHANGELOG.md) entry for this change
- Update the coverage checkbox (see the Contributing [docs](https://github.com/hashicorp/go-tfe/blob/main/docs/CONTRIBUTING.md#adding-new-functionality-or-fixing-relevant-bugs) for more info)

Thank you! ✨

**Comment by estenssoros** [comment]
hey hey, i'm finally able to sign the contributing docs since I am not longer with my previous employer. I'm going to close and reopen this PR to avoid merge conflicts

**Pull request closed without merging**
