### PR TITLE
Adds dd test optimization integration

### PR DESCRIPTION
**Pull request by brandonc**
See comment below 🤞👇  ¯\_(ツ)_/¯ 

The report below will outline tests coverage % decreases, flaky tests, etc whenever they apply to the PR. Similar to this:

image (2)

### CODE REVIEW

**Comment by barrettclark** [comment]
Should the `cover.out` file be included? Will it be updated as code and tests evolve?

**Comment by brandonc** [comment]
No, it's transient and used to report the number to datadog

**Comment by barrettclark** [comment]
That's what I thought. It looks like you included it in this PR, though. If it shouldn't be then it could also be helpful to include that in the `.gitignore` file.

**Comment by brandonc** [comment]
OOPS!

**Review by barrettclark — APPROVED** [review]

**Review by Maed223 — APPROVED** [review]

**Pull request merged**
