### PR TITLE
🔧 Bump the circleci resource class when we run

### PR DESCRIPTION
**Pull request by annawinkler**
## Description

Bump the resource class to something reasonable.

### CODE REVIEW

**Comment by brandonc** [comment]
I'm curious about the indications that the CI machine doesn't have enough resources. I would imagine testing the client should not be very intense because it is often waiting on the API. Also it may be worth noting that atlas/tflocal is not running in circle and isn't affected by this bump.

**Comment by annawinkler** [comment]
That's a great question! Here is a screenshot of what CircleCI indicated on another build:
Screen Shot 2022-05-17 at 4 43 58 PM

I figured it was worth a try. And it sounds like the larger resource is included in our plan.

**Comment by brandonc** [comment]
I think this is basically a dark pattern to juice sales because, while larger resources are included, they cost more credits per time unit. I think we should leave it as is unless a green run on this branch is substantially faster than main.

**Comment by annawinkler** [comment]
Because we've been having consistent test failures, it's hard to tell if this change would help or not. I guess we could get the test failures fixed and then evaluate the performance.

**Comment by annawinkler** [comment]
I'm going to close this for now. When I've run the tests, they take about 10 minutes. Maybe that's fine? 🔥

**Pull request closed without merging**
