### PR TITLE
Bump go-version to the latest 1.6.0

### PR DESCRIPTION
**Pull request by annawinkler**
## Description

Bump go-version to the latest 1.6.0

## Testing plan

1. Verify tests pass

### CODE REVIEW

**Comment by annawinkler** [comment]
Verified that the failing test passes locally:

```awinkler•~/dev/go-tfe(aw/bump-go-version-1.6.0)» envchain tfe-local go test -run TestStateVersionsRead -v ./... -tags=integration                [13:56:58]

=== RUN   TestStateVersionsRead
=== RUN   TestStateVersionsRead/when_the_state_version_exists
=== RUN   TestStateVersionsRead/when_the_state_version_does_not_exist
=== RUN   TestStateVersionsRead/with_invalid_state_version_id
--- PASS: TestStateVersionsRead (22.19s)
    --- PASS: TestStateVersionsRead/when_the_state_version_exists (8.38s)
    --- PASS: TestStateVersionsRead/when_the_state_version_does_not_exist (0.26s)
    --- PASS: TestStateVersionsRead/with_invalid_state_version_id (0.00s)
=== RUN   TestStateVersionsReadWithOptions
=== RUN   TestStateVersionsReadWithOptions/when_the_state_version_exists
--- PASS: TestStateVersionsReadWithOptions (7.93s)
    --- PASS: TestStateVersionsReadWithOptions/when_the_state_version_exists (0.30s)
PASS
ok  	github.com/hashicorp/go-tfe	30.297s
?   	github.com/hashicorp/go-tfe/examples/organizations	[no test files]
?   	github.com/hashicorp/go-tfe/examples/workspaces	[no test files]
?   	github.com/hashicorp/go-tfe/mocks	[no test files]
```

**Review by laurenolivia — APPROVED** [review]
👍

**Comment by annawinkler** [comment]
I think the test failure might be a real one - I'll dig into that tomorrow.

**Review by brandonc — APPROVED** [review]
What difficulty did we face with the dependabot PR? I'd like to get the dependabot workflow working if possible.

**Comment by annawinkler** [comment]
> What difficulty did we face with the dependabot PR? I'd like to get the dependabot workflow working if possible.

No difficulty - I had opened this PR before dependabot though so I kept this one and closed the dependabot PR. 🚀

**Pull request merged**
